<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="49" started-at="2018-03-21T12:39:06Z" finished-at="2018-03-21T12:39:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="49" started-at="2018-03-21T12:39:06Z" finished-at="2018-03-21T12:39:06Z">
      <class name="com.qtpselenium.hybrid.suiteb.TestC">
        <test-method status="FAIL" signature="bookTicket()[pri:0, instance:com.qtpselenium.hybrid.suiteb.TestC@3c5a99da]" name="bookTicket" duration-ms="17" started-at="2018-03-21T18:09:06Z" finished-at="2018-03-21T18:09:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failure Message]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failure Message
	at org.junit.Assert.fail(Assert.java:93)
	at com.qtpselenium.hybrid.suiteb.TestC.bookTicket(TestC.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bookTicket -->
        <test-method status="SKIP" signature="checkTicket()[pri:0, instance:com.qtpselenium.hybrid.suiteb.TestC@3c5a99da]" name="checkTicket" duration-ms="1" started-at="2018-03-21T18:09:06Z" depends-on-methods="com.qtpselenium.hybrid.suiteb.TestC.bookTicket" finished-at="2018-03-21T18:09:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkTicket -->
        <test-method status="SKIP" signature="cancelTicket()[pri:0, instance:com.qtpselenium.hybrid.suiteb.TestC@3c5a99da]" name="cancelTicket" duration-ms="1" started-at="2018-03-21T18:09:06Z" depends-on-methods="com.qtpselenium.hybrid.suiteb.TestC.bookTicket, com.qtpselenium.hybrid.suiteb.TestC.checkTicket" finished-at="2018-03-21T18:09:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cancelTicket -->
      </class> <!-- com.qtpselenium.hybrid.suiteb.TestC -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
